# Travis CI Configuration
#
# https://docs.travis-ci.com/
# https://docs.travis-ci.com/user/languages/cpp/
#
# Example with multiple compiler versions, including both GCC and Clang
# https://github.com/facebook/fatal/blob/dev/.travis.yml
#
# OSX Xcode and Clang versions
# https://trac.macports.org/wiki/XcodeVersionInfo


# Test
script:
 - make -j4 && make test

# Always test the master branch, even when there's no pull request
branches:
  only:
    - master

# Test against multiple compiler versions
language: cpp
matrix:
  include:

    - name: "Ubuntu 14.04 Trusty GCC 4.8"
      os: linux
      dist: trusty
      compiler: gcc

    - name: "Ubuntu 14.04 Trusty Clang 3.5"
      os: linux
      dist: trusty
      compiler: clang

    -name: "Ubuntu 16.04 Xenial GCC 5.4"
      os: linux
      dist: xenial
      compiler: gcc

    - name: "Ubuntu 16.04 Xenial Clang 7"
      os: linux
      dist: xenial
      compiler: clang

    - name: "Ubuntu 16.04 Xenial GCC 6"
      os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-6
      env: MATRIX_EVAL="CXX=g++-6"

    # - name: "Ubuntu 16.04 Xenial GCC 7"
    #   os: linux
    #   dist: xenial
    #   compiler: gcc
    #   addons:
    #     apt:
    #       sources: ubuntu-toolchain-r-test
    #       packages: g++-7
    #   env: MATRIX_EVAL="CXX=g++-7"

    # - name: "macOS 10.11 Aplle LLVM version FIXME"
    #  os: osx
    #  osx_image: xcode8
    #  compiler: clang

    - name: "macOS 10.12 Apple LLVM version 9.0.0"
      os: osx
      osx_image: xcode9.2
      compiler: clang

    - name: "macOS 10.13 Apple LLVM version 10.0.0"
      os: osx
      osx_image: xcode10.1
      compiler: clang

before_install:
    - eval "${MATRIX_EVAL}"
